### ISSUE TITLE
Welcome Page 

### ISSUE THREAD

**Issue by joelhari** [scg-unibe-ch/ese2019-team1#14]
The pictures on the welcome page cover up the start-button, if the page is shown on a wide screen. This also makes it impossible to press the start-button.

![Screenshot (2)](https://user-images.githubusercontent.com/55575727/69947699-7a9b6e00-14ee-11ea-9053-73a32ad9034c.png)

**Comment by v-WU** [comment]
This problem still happenes on the second and third slide :/
