### ISSUE TITLE
route from feed to setting page does not work

### ISSUE THREAD

**Issue by octojoint** [scg-unibe-ch/ese2019-team1#2]
Bug occurs right after login and you're at the feed page and wish to go directly to the settings page, it wont load until you change to another page

ERROR Error: "No value accessor for form control with unspecified name attribute"   SettingsPage.html:16:4

ERROR Error: "Uncaught (in promise): Error: No value accessor for form control with unspecified name attribute 
core.js:9110:19

**Comment by joelhari** [comment]
Resolved the bug with the following commit

https://github.com/scg-unibe-ch/ese2019-team1/commit/71372fafbe5f7bb6ab292f233f5d525357075add
