### ISSUE TITLE
Fehlermeldung beim Settingsbutton

### ISSUE THREAD

**Issue by v-WU** [scg-unibe-ch/ese2019-team1#5]
Der settingsbutton wirft folgende Fehlermeldung:
![image](https://user-images.githubusercontent.com/55547478/69066945-884af100-0a22-11ea-91e8-8b72c79b206c.png)

**Comment by octojoint** [comment]
mhh firebase storage...sounds like this is my bad :(

**Comment by octojoint** [comment]
solved: enviroment was missing variable for storage container, pushed fix
